name: Deploy to Production

on:
  push:
    branches:
      - main # or any branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify your Node.js version here

    - name: Install dependencies
      run: npm install --frozen-lockfile

    - name: Build
      run: pnpm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Adjust this path if your built files are located elsewhere
